neo4j:
  name: "${NEO4J_INSTANCE_NAME}"
  resources:
    cpu: "8"
    memory: "8Gi"

  password: "${NEO4J_PASSWORD}"

  # Uncomment to use enterprise edition
  #edition: "enterprise"
  edition: "eval"
  #acceptLicenseAgreement: "yes"
env:
  NEO4J_PLUGINS: '["apoc"]'
  APOC_EXPORT_FILE_ENABLED: "true"
config:
  dbms.security.procedures.unrestricted: "gds.*,apoc.*"
  dbms.security.procedures.allowlist: "gds.*,apoc.*"
volumes:
  data:
    mode: "dynamic"
    dynamic:
      # In GKE;
      # * premium-rwo provisions SSD disks (recommended)
      # * standard-rwo provisions balanced SSD-backed disks
      # * standard provisions HDD disks
      storageClassName: premium-rwo