neo4j:
  name: neo4j
  resources:
    cpu: "0.5"
    memory: "2Gi"

  # Uncomment to set the initial password
  #password: "neo4j"

  # Uncomment to use enterprise edition
  #edition: "enterprise"
  #acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi

# Neo4j configuration (yaml format)
#config:
#  server.metrics.enabled: "true"
#  server.metrics.csv.interval: "10s"
#  server.metrics.csv.rotation.keep_number: "2"
#  server.metrics.csv.rotation.compression: "NONE"

# Jvm configuration for Neo4j
#jvm:
#  additionalJvmArguments:
#  - "-XX:+HeapDumpOnOutOfMemoryError"
#  - "-XX:HeapDumpPath=/logs/neo4j.hprof"
