apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: svph-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/${PROJECT_ID}/secrets/SCANR_ES_HOST/versions/${SECRET_VERSION}"
        path: "SCANR_ES_HOST.txt"
      - resourceName: "projects/${PROJECT_ID}/secrets/SCANR_ES_USER/versions/${SECRET_VERSION}"
        path: "SCANR_ES_USER.txt"
      - resourceName: "projects/${PROJECT_ID}/secrets/SCANR_ES_PASSWORD/versions/${SECRET_VERSION}"
        path: "SCANR_ES_PASSWORD.txt"