apiVersion: v1
kind: Service
metadata:
  labels:
    app: sovisuplus
  name: sovisuplus-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sovisuplus
  type: LoadBalancer
