apiVersion: v1
kind: Service
metadata:
  labels:
    app: crisalid-org-registry
  name: crisalid-org-registry
spec:
  ports:
    - name: "crisalid-org-registry-port"
      port: 3000
      targetPort: 3000
  selector:
    app: crisalid-org-registry
