apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crisalid-bus
  name: crisalid-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crisalid-bus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crisalid-bus
    spec:
      containers:
        - image: rabbitmq:3-management
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            failureThreshold: 30
            periodSeconds: 1
            timeoutSeconds: 3
          name: crisalid-bus
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: crisalid-bus-secret
                  key: amqp_password
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: crisalid-bus-secret
                  key: amqp_user
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: crisalid-bus-data
            - mountPath: /var/log/rabbitmq
              name: crisalid-bus-logs
      restartPolicy: Always
      volumes:
        - name: crisalid-bus-data
          persistentVolumeClaim:
            claimName: crisalid-bus-pvc-data
        - name: crisalid-bus-logs
          persistentVolumeClaim:
            claimName: crisalid-bus-pvc-logs
