apiVersion: v1
kind: Secret
metadata:
  name: sovisuplus-secret
data:
  db_host: "${SVP_DB_HOST}"
  db_port: "${SVP_DB_PORT}"
  db_name: "${SVP_DB_NAME}"
  db_user: "${SVP_DB_USER}"
  db_password: "${SVP_DB_PASSWORD}"
  nextauth_secret: "${NEXTAUTH_SECRET}"
  keycloak_client_secret: "${KEYCLOAK_CLIENT_SECRET}"
  graphql_api_key: '${SVP_GRAPHQL_API_KEY}'
  orcid_client_id: "${ORCID_CLIENT_ID}"
  orcid_client_secret: "${ORCID_CLIENT_SECRET}"