apiVersion: v1
kind: Secret
metadata:
  name: svph-api-secret
data:
  scanr_es_password: "${SCANR_ES_PASSWORD}"
  scanr_es_user: "${SCANR_ES_USER}"
  scanr_es_host: "${SCANR_ES_HOST}"
  scopus_api_key: "${SCOPUS_API_KEY}"
  scopus_inst_token: "${SCOPUS_INST_TOKEN}"
