apiVersion: v1
kind: ConfigMap
metadata:
  name: crisalid-training-data-config
  labels:
    app: crisalid-training-data
data:
  AMQP_HOST: '${AMQP_HOST}'
  AMQP_PORT: '${AMQP_PORT}'
  APP_ENV: ${APP_ENV}
  AMQP_PREFETCH_COUNT: '1'


