apiVersion: v1
kind: ConfigMap
metadata:
  name: sovisuplus-config
  labels:
    app: sovisuplus
data:
  APP_ENV: '${APP_ENV}'
  APP_URL: '${SOVISUPLUS_HOST}'
  INSTITUTION_NAME: '${INSTITUTION_NAME}'
  KEYCLOAK_CLIENT_ID: '${KEYCLOAK_CLIENT_ID}'
  KEYCLOAK_ADDR: '${KEYCLOAK_ADDR}'
  KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
  GRAPHQL_ENDPOINT_ENABLED: 'true'
  GRAPHQL_ENDPOINT_URL: 'http://apollo/graphql'
  GRAPHQL_API_KEY_ENABLED: 'true'
  AMQP_HOST: '${AMQP_HOST}'
  AMQP_PORT: '${AMQP_PORT}'
  AMQP_QUEUE_NAME: '${SVP_AMQP_QUEUE_NAME}'
  NEXT_PUBLIC_SUPPORTED_LOCALES: "fr,en"



