apiVersion: v1
kind: ConfigMap
metadata:
  name: svph-api-worker-config
  labels:
    app: svph-api-worker
data:
  AMQP_ENABLED: 'true'
  AMQP_HOST: '${AMQP_HOST}'
  AMQP_PORT: '${AMQP_PORT}'
  APP_ENV: ${APP_ENV}
  AMQP_PREFETCH_COUNT: '1'
  INNER_TASK_PARALLELISM_LIMIT: '1'
  INNER_TASK_QUEUE_LENGTH: '1'
  AMQP_CONSUMER_ACK_TIMEOUT: '3000'


